.TH NEATLD 1 
.SH NAME
neatld \- the neatld ARM/X86(-64) static linker
.SH SYNOPSIS
.B neatld
[
.I options
]
.I objfile ...
.br
.SH DESCRIPTION
neatld links the given object and archive files into an executable
file.  The architecture of the output is determined based on the
architecture of input files.  Options are:
.TP
.BI -o " out"
Write the output to the given file instead of
.I a.out.
.TP
.BI -l lib
Link with library
.IR lib .
.TP
.BI -L libdir
Search
.IR libdir
for finding libraries specified with
.B -l.
.TP
.BI -s
Do not include a symbol table.
.TP
.BI -m X=vaddr:laddr
Set the virtual/load address of a section.
.I X
defines the section and can be
.I c
for code section,
.I d
for data section and
.I b
for BSS section.
.IR laddr
can be omitted, in which case it would be the same as
.IR vaddr .
.TP
.BI -p
Page-align sections.
.TP
.BI -e sym
Entry point symbol.
.SH "SEE ALSO"
.IR neatcc (1),
.IR neatas (1)
